/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wiiisdom.logsplitter;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jean-francois.cayron
 */
public class LogSplitterUI extends javax.swing.JFrame {

    /**
     * Creates new form LogSplitterUI
     */
    public LogSplitterUI() {
        initComponents();
        SetExecute();
        CreateChoosers();
    }

    private boolean hasInput = false;
    private boolean hasOutput = false;
    private JFileChooser inputChooser;
    private JFileChooser outputChooser;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        txtSourceLog = new javax.swing.JTextField();
        txtOutFolder = new javax.swing.JTextField();
        btnOutFolder = new javax.swing.JButton();
        btnSourceLog = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wiiisdom LogSplitter");

        txtSourceLog.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSourceLog.setEnabled(false);
        txtSourceLog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                onTxtSourceLogFocusOut(evt);
            }
        });

        txtOutFolder.setActionCommand("<Not Set>");
        txtOutFolder.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtOutFolder.setEnabled(false);

        btnOutFolder.setText("Browse ...");
        btnOutFolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onBrowseOutFolderClicked(evt);
            }
        });

        btnSourceLog.setText("Browse ...");
        btnSourceLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onBrowseSourceClick(evt);
            }
        });

        btnExecute.setText("Split");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onExecuteClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSourceLog)
                            .addComponent(txtOutFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSourceLog)
                            .addComponent(btnOutFolder)))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnExecute)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(btnSourceLog)
                        .addGap(18, 18, 18)
                        .addComponent(btnOutFolder))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSourceLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txtOutFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(btnExecute)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onBrowseSourceClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onBrowseSourceClick
        int returnVal = inputChooser.showOpenDialog(pnlBase);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = inputChooser.getSelectedFile();
            Helper.setInputFile(file);
            txtSourceLog.setText(file.getAbsolutePath());
            hasInput = true;
            SetExecute();

        }
    }//GEN-LAST:event_onBrowseSourceClick

    private void onBrowseOutFolderClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onBrowseOutFolderClicked
        int returnVal = outputChooser.showSaveDialog(pnlBase);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = outputChooser.getSelectedFile();
            String path = file.getAbsolutePath();
            if (!path.substring(path.length() - 5).equalsIgnoreCase(".XLSX")) {
                path = path.concat(".XLSX");
                file = new File(path);
            }
            Helper.setOutputFile(file);
            txtOutFolder.setText(path);
            hasOutput = true;
            SetExecute();
        }
    }//GEN-LAST:event_onBrowseOutFolderClicked

    private void onExecuteClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onExecuteClicked
        try {
            Helper.RunFile();
        } catch (IOException ex) {
            Logger.getLogger(LogSplitterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(pnlBase,
                "Extraction complete.\nFile " + txtOutFolder.getText() + " is ready",
                "Process Complete",
                JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_onExecuteClicked

    private void onTxtSourceLogFocusOut(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_onTxtSourceLogFocusOut
        // TODO add your handling code here:
    }//GEN-LAST:event_onTxtSourceLogFocusOut

    private void SetExecute() {
        btnExecute.setEnabled(hasInput && hasOutput);
    }

    private void CreateChoosers() {
        inputChooser = new JFileChooser();
        inputChooser.addChoosableFileFilter(newFilter("Log files", "log"));
        inputChooser.addChoosableFileFilter(newFilter("Text files", "txt"));
        inputChooser.setAcceptAllFileFilterUsed(false);

        outputChooser = new JFileChooser();
        outputChooser.addChoosableFileFilter(newFilter("XLSX files", "xlsx"));
        outputChooser.setAcceptAllFileFilterUsed(false);
    }

    private FileNameExtensionFilter newFilter(String description, String... extensions) {
        return new FileNameExtensionFilter(description, extensions);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogSplitterUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LogSplitterUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnOutFolder;
    private javax.swing.JButton btnSourceLog;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JTextField txtOutFolder;
    private javax.swing.JTextField txtSourceLog;
    // End of variables declaration//GEN-END:variables
}
